### PR TITLE
Timeline Drawer

### PR DESCRIPTION
**Pull request by alexandergknoll**
@garrettdashnelson I think we'll likely want to make some tweaks, but this is a good starting point.  Two important things I've noticed which are regressions from the existing implementation:

1. I don't think the map ID is in the dataset for the timeline that would be needed to link out to the map
2. I don't think there's an image in the dataset for each map

### CODE REVIEW

**Comment by garrettdashnelson** [comment]
@alexandergknoll This looks visually great.

Ideally I think that the `maps` parameter of the `openDrawer` should take an array of map identifiers and nothing else. This is actually what is being executed on line 48 where the button indicating maps associated with an event triggers `openDrawer(event.solr_ids_array)`. 

The trouble is coming from the other time this function is called, on line 32, where the button is supposed to trigger all the maps associated with a given year. (`<a @click="openDrawer(data.timeline_events[parseInt(year)])" class="tooltip">`) That's garbage data anyhow, so let's simply remove that element and leave _only_ the "_n_ related maps" button, which should pass correct data? 

That way the store `drawerMaps` can expect to get the array of IDs, and use it to populate a set of mini map cards/list. Does that make sense?

**Comment by alexandergknoll** [comment]
@garrettdashnelson thanks for your help with that - makes perfect sense!  Let me know if I got it a bit closer with these edits

**Comment by garrettdashnelson** [comment]
This looks great to me! @almontg & @hkemp2128 any feedback? https://deploy-preview-88--argo-astro-dev.netlify.app/

**Comment by hkemp2128** [comment]
image

**Comment by almontg** [comment]
This looks great! Henry and I just chatted very breifly and both agree that we like the size of the thumbnails and amount of info. My one note here is that it covers up the timeline UI so you can't really browse or read other entries without closing the sidebar, but I'm fine with this for now

**Comment by alexandergknoll** [comment]
@garrettdashnelson I made that top bar sticky so that it's persistent when scrolling!

**Review by garrettdashnelson — APPROVED** [review]

**Pull request merged**
